# Generated by Django 6.1.1 on 2026-09-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
